language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
env:
  matrix:
    - "DATABASE=mysql"
    - "DATABASE=pg"
    - "DATABASE=sqlite3"
rvm:
  - 2.1
  - 2.2
matrix:
  fast_finish: true
notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
